language: python

python:
   - "3.6"

install:
 - pip install -r requirements.txt
 - pip install coverage
 - pip install coveralls
 - pip install pytest pytest-cov

before_install:
 - git clone -b develope https://github.com/Njaya2019/storemanager-endpoints-v2.git
 - cd storemanager-endpoints-v2
 
script:
 - pytest --cov=.

after_success:
 - coveralls
