language: python

python:
   - "3.6"

install:
 - pip install -r requirements.txt
 - pip install coverage
 - pip install coveralls
 - pip install pytest pytest-cov

services:
 - postgresql

before_install:
 - psql -c 'ALTER USER postgres WITH PASSWORD 'a1990n';'
 - psql -c 'create database store_db;' -U postgres
 - psql -c 'USE store_db; CREATE TABLE IF NOT EXISTS products(product_id SERIAL PRIMARY KEY,product_name VARCHAR(255) NOT NULL,product_price INT NOT NULL,product_qty INT NOT NULL);'
 - psql -c 'USE store_db; CREATE TABLE IF NOT EXISTS sales(sale_id SERIAL PRIMARY KEY,attendant_id INT NOT NULL,product_id INT NOT NULL,sale_quantity INT NOT NULL,tnx_date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP);'
 - psql -c 'USE store_db; CREATE TABLE IF NOT EXISTS users(userid SERIAL PRIMARY KEY,user_fullname VARCHAR(50) NOT NULL,user_email VARCHAR(50) NOT NULL,user_role VARCHAR(50) NOT NULL,user_password TEXT NOT NULL);'
 - psql -c 'USE store_db; alter table sales add foreign key (product_id) REFERENCES products(product_id);'
 - git clone -b develope https://github.com/Njaya2019/storemanager-endpoints-v2.git
 - cd storemanager-endpoints-v2
 
script:
 - pytest --cov=.

after_success:
 - coveralls
